import 'package:json_annotation/json_annotation.dart';

import '../../serialization/my_fatoorah_decimal_converter.dart';
import '../../serialization/my_fatoorah_json.dart';

part 'make_refund_response.g.dart';

/// Data returned by `POST /v2/MakeRefund`.
@JsonSerializable()
final class MakeRefundResponse {
  /// Creates a MakeRefund response.
  const MakeRefundResponse({
    required this.key,
    required this.refundId,
    required this.refundReference,
    required this.refundInvoiceId,
    required this.amount,
    this.comment,
    this.externalIdentifier,
  });

  /// Key value passed for the request transaction.
  @JsonKey(name: 'Key')
  final String key;

  /// Refund request ID.
  @JsonKey(name: 'RefundId')
  final int refundId;

  /// Refund reference generated by MyFatoorah.
  @JsonKey(name: 'RefundReference')
  final String refundReference;

  /// Invoice ID of the refunded amount.
  @MyFatoorahDecimalConverter()
  @JsonKey(name: 'RefundInvoiceId')
  final String refundInvoiceId;

  /// Amount to be refunded.
  @MyFatoorahDecimalConverter()
  @JsonKey(name: 'Amount')
  final String amount;

  /// Comments passed in the request.
  @JsonKey(name: 'Comment')
  final String? comment;

  /// External identifier passed in the request.
  @JsonKey(name: 'ExternalIdentifier')
  final String? externalIdentifier;

  /// Creates a MakeRefund response from JSON.
  factory MakeRefundResponse.fromJson(Map<String, Object?> json) =>
      _$MakeRefundResponseFromJson(json);

  /// Converts this response to JSON.
  Map<String, Object?> toJson() {
    return MyFatoorahJson.withoutNulls(_$MakeRefundResponseToJson(this));
  }
}
